vich_uploader:
    db_driver: orm

    mappings:
      subjectresponses:
          uri_prefix: /images/subjectresponses
          upload_destination: '%kernel.project_dir%/public/images/subjectresponses'
          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true

