CreateReservation:
  path: /api/CreaterReservation/{nom}/{prenom}/{nbrplace}/{id}
  controller: App\Controller\APIController::CreaterReservationAction
AllReservation:
  path: /AllReservation
  controller: App\Controller\APIController::AllReservationAction
DeleteArticle:
  path:     api/DeleteReservation/{id}
  controller: App\Controller\APIController::DeleteReservationAction